### ISSUE TITLE
ID Error

### ISSUE THREAD

**Issue by iCallH4x** [Dev-CasperTheGhost/snaily-cad#2]
code: 'ER_NO_DEFAULT_FOR_FIELD',
  errno: 1364,
  sqlMessage: "Field 'id' doesn't have a default value",
  sqlState: 'HY000',
  index: 0,
  sql: "INSERT INTO users (`username`, `password`, `rank`, `leo`, `ems_fd`, `dispatch`, `banned`, `ban_reason`, `whitelist_status`) VALUES ('iCallH4x', '$2b$15$/TszLjWBZ7gQKR/EUMSaA.KSMq3ISxhUIjjsOohcEAwLc5FhjBsv6', 'owner', 'yes', 'yes', 'yes', '', '', 'accepted'); INSERT INTO `cad_info` (`owner`, `cad_name`, `AOP`, `whitelisted`) VALUES ('iCallH4x', 'Change Me', 'Change Me', 'false')"

**Comment by casperiv0** [comment]
Hello there

Did you have any error importing the `snail-cad.sql` file?


Sorry for the inconvenience.

**Comment by iCallH4x** [comment]
It was an error with the permissions on the SQL user, sorry for blaming the resource!

Thank you for the quick response also.

**Comment by casperiv0** [comment]
Ah okay! 

No problem and stay safe!
