### ISSUE TITLE
I really love this CAD I have a question though.

### ISSUE THREAD

**Issue by sonicisdeadtome** [Dev-CasperTheGhost/snaily-cad#3]
I was able to successfully setup and run the CAD on a spare PC I just bought a new domain and was curious do you think it's possible to host the CAD there. I don't know a ton about the server process. If If I uploaded everything from the repository there including the node modules and made a mySQL database in Phpmyadmin and got all that setup would you think it could run.

**Comment by sonicisdeadtome** [comment]
I figured out how to go about this process. Sorry for opening an issue have a great day.

**Comment by casperiv0** [comment]
It's okay, glad to hear all is working! 

stay safe! 
Casper
