### ISSUE TITLE
When trying to do "Npm install" on the server folder i get this error

### ISSUE THREAD

**Issue by nightking2002** [Dev-CasperTheGhost/snaily-cad#5]
**Describe the bug**
When trying to do "Npm install" on the server folder i get this error

**To Reproduce**
1. Followed your steps exactly and get this error when coming to that point

`node-pre-gyp WARN Using needle for node-pre-gyp https download
node-pre-gyp WARN Pre-built binaries not installable for bcrypt@4.0.1 and node@12.17.0 (node-v72 ABI, unknown) (falling back to source compile with node-gyp)
node-pre-gyp WARN Hit error Remote end closed socket abruptly.
gyp ERR! find VS
gyp ERR! find VS msvs_version was set from command line or npm config
gyp ERR! find VS - looking for Visual Studio version 2015
gyp ERR! find VS VCINSTALLDIR not set, not running in VS Command Prompt
gyp ERR! find VS checking VS2019 (16.6.30128.74) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v142
gyp ERR! find VS - found Windows SDK: 10.0.18362.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS checking VS2017 (15.9.28307.1146) found at:
gyp ERR! find VS "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS - found "Visual Studio C++ core features"
gyp ERR! find VS - found VC++ toolset: v141
gyp ERR! find VS - found Windows SDK: 10.0.17763.0
gyp ERR! find VS - msvs_version does not match this version
gyp ERR! find VS could not find a version of Visual Studio 2017 or newer to use
gyp ERR! find VS looking for Visual Studio 2015
gyp ERR! find VS - not found
gyp ERR! find VS not looking for VS2013 as it is only supported up to Node.js 8
gyp ERR! find VS
gyp ERR! find VS valid versions for msvs_version:
gyp ERR! find VS - "2019"
gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2019\Community"
gyp ERR! find VS - "2017"
gyp ERR! find VS - "C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools"
gyp ERR! find VS
gyp ERR! find VS **************************************************************
gyp ERR! find VS You need to install the latest version of Visual Studio
gyp ERR! find VS including the "Desktop development with C++" workload.
gyp ERR! find VS For more information consult the documentation at:
gyp ERR! find VS https://github.com/nodejs/node-gyp#on-windows
gyp ERR! find VS **************************************************************
gyp ERR! find VS
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Visual Studio installation to use
gyp ERR! stack     at VisualStudioFinder.fail (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:121:47)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:74:16
gyp ERR! stack     at VisualStudioFinder.findVisualStudio2013 (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:351:14)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:70:14
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\find-visualstudio.js:372:16
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:54:7
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\util.js:33:16
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:310:5)
gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
gyp ERR! System Windows_NT 10.0.17763
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "configure" "--fallback-to-build" "--module=C:\\Users\\Administrator\\snaily-cadv2\\server\\node_modules\\bcrypt\\lib\\binding\\napi-v3\\bcrypt_lib.node" "--module_name=bcrypt_lib" "--module_path=C:\\Users\\Administrator\\snaily-cadv2\\server\\node_modules\\bcrypt\\lib\\binding\\napi-v3" "--napi_version=6" "--node_abi_napi=napi" "--napi_build_version=3" "--node_napi_label=napi-v3" "--python=C:\\Users\\Administrator\\AppData\\Local\\Programs\\Python\\Python38\\python.exe" "--msvs_version=2015"
gyp ERR! cwd C:\Users\Administrator\snaily-cadv2\server\node_modules\bcrypt
gyp ERR! node -v v12.17.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Administrator\snaily-cadv2\server\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Administrator\snaily-cadv2\server\node_modules\bcrypt\lib\binding\napi-v3 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3 --python=C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python.exe --msvs_version=2015' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Users\Administrator\snaily-cadv2\server\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:315:20)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:1021:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
node-pre-gyp ERR! System Windows_NT 10.0.17763
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\snaily-cadv2\\server\\node_modules\\node-pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Users\Administrator\snaily-cadv2\server\node_modules\bcrypt
node-pre-gyp ERR! node -v v12.17.0
node-pre-gyp ERR! node-pre-gyp -v v0.14.0
node-pre-gyp ERR! not ok
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=C:\Users\Administrator\snaily-cadv2\server\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node --module_name=bcrypt_lib --module_path=C:\Users\Administrator\snaily-cadv2\server\node_modules\bcrypt\lib\binding\napi-v3 --napi_version=6 --node_abi_napi=napi --napi_build_version=3 --node_napi_label=napi-v3 --python=C:\Users\Administrator\AppData\Local\Programs\Python\Python38\python.exe --msvs_version=2015' (1)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! bcrypt@4.0.1 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the bcrypt@4.0.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-06-02T18_58_25_369Z-debug.log`

**Comment by casperiv0** [comment]
Hey!

It might be because of permissions on your operating system, try to run `sudo npm install`

Thanks! 
Casper

**Comment by casperiv0** [comment]
Oh and make sure the latest version of Visual Studio is installed as well. (Shows in the error)

**Comment by nightking2002** [comment]
I'm running it on windows vps not sure if sudo works then

Den tis 2 juni 2020 21:03Casper <notifications@github.com> skrev:

**Comment by nightking2002** [comment]
I'm also pretty sure I have, thanks for the fast responses btw:)

Den tis 2 juni 2020 21:04Casper <notifications@github.com> skrev:

**Comment by casperiv0** [comment]
No problem!

I've investigated the issue and it seems you don't have the latest version of Python installed, also I suggest you to download https://github.com/felixrieseberg/windows-build-tools and https://www.microsoft.com/en-us/download/details.aspx?id=52685, since you're on a windows VPS some stuff might be outdated.

Casper

**Comment by nightking2002** [comment]
hm doesn't seem to work I've tried something similar before I mailed you..
still get the same error

Den tis 2 juni 2020 kl 21:23 skrev Casper <notifications@github.com>:

**Comment by casperiv0** [comment]
It's weird, it isn't an issue with the CAD itself either, I suggest googling the issue,

Also this might help? 
![Screenshot 2020-06-02 at 21 36 05](https://user-images.githubusercontent.com/53900565/83562021-231ba080-a519-11ea-8196-f5c036f0f487.png)

**Comment by nightking2002** [comment]
Ops sorry I thought that I had the right version of python reinstalling the
correct version now give me a minute ill see if it works

Den tis 2 juni 2020 kl 21:32 skrev Jesper Nilsson <
jespernilsson2002@gmail.com>:

**Comment by nightking2002** [comment]
No, it doesn't seem to be a problem with the cad I've tried it both on my
personal computer and the VPS now so I don't know ill troubleshoot some
more see if I find the issue. Thanks a lot for the help!

Den tis 2 juni 2020 kl 21:37 skrev Casper <notifications@github.com>:

**Comment by casperiv0** [comment]
Yeah no problem!

**Comment by nightking2002** [comment]
Sorry to bother you more, but I fixed the problem I had before however now
it can't find the "serve" while attempting to start.

Den tis 2 juni 2020 kl 21:47 skrev Casper <notifications@github.com>:

**Comment by casperiv0** [comment]
Make sure to run `yarn global add serve` in the client folder, after you run `npm run build` in the client folder

I will be getting of for the night though, if there’s any other issue send them and I’ll reply tomorrow asap :)

**Comment by nightking2002** [comment]
Yea, same Good Night! I did do it that way I just always find a way to make
things not work.

Den tis 2 juni 2020 kl 22:23 skrev Casper <notifications@github.com>:

**Comment by casperiv0** [comment]
If this wouldn't work then I wouldn't know.

 ![Screenshot 2020-06-02 at 21 36 05](https://user-images.githubusercontent.com/53900565/83562021-231ba080-a519-11ea-8196-f5c036f0f487.png)

**Comment by nightking2002** [comment]
I got through that error however now when i do "npm start" i get this:

PS C:\Users\Administrator\snaily-cadv2> npm start

> snailycad-v2@1.2.0 start C:\Users\Administrator\snaily-cadv2
> concurrently "npm run server" "npm run client"

[0]
[0] > snailycad-v2@1.2.0 server C:\Users\Administrator\snaily-cadv2
[0] > npm start --prefix server
[0]
[1]
[1] > snailycad-v2@1.2.0 client C:\Users\Administrator\snaily-cadv2
[1] > npm run serve --prefix client
[1]
[1]
[1] > client@0.1.0 serve C:\Users\Administrator\snaily-cadv2\client
[1] > serve -s build -l 80
[1]
[0]
[0] > snailycad-server@1.0.0 start
C:\Users\Administrator\snaily-cadv2\server
[0] > nodemon server.js
[0]
[1] 'serve' is not recognized as an internal or external command,
[1] operable program or batch file.
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! client@0.1.0 serve: `serve -s build -l 80`
[1] npm ERR! Exit status 1
[1] npm ERR!
[1] npm ERR! Failed at the client@0.1.0 serve script.
[1] npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!
C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-06-03T12_24_58_848Z-debug.log
[1] npm ERR! code ELIFECYCLE
[1] npm ERR! errno 1
[1] npm ERR! snailycad-v2@1.2.0 client: `npm run serve --prefix client`
[1] npm ERR! Exit status 1
[1] npm ERR!
npm ERR! Failed at the snailycad-v2@1.2.0 client script.
[1] npm ERR! This is probably not a problem with npm. There is likely
additional logging output above.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR!
C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-06-03T12_24_59_007Z-debug.log
[1] npm run client exited with code 1
[0] [nodemon] 2.0.4
[0] [nodemon] to restart at any time, enter `rs`
[0] [nodemon] watching path(s): *.*
[0] [nodemon] watching extensions: js,mjs,json
[0] [nodemon] starting `node server.js`
[0] internal/modules/cjs/loader.js:969
[0]   throw err;
[0]   ^
[0]
[0] Error: Cannot find module
'C:\Users\Administrator\snaily-cadv2\server\node_modules\bcrypt\lib\binding\napi-v3\bcrypt_lib.node'
[0] Require stack:
[0] -
C:\Users\Administrator\snaily-cadv2\server\node_modules\bcrypt\bcrypt.js
[0] - C:\Users\Administrator\snaily-cadv2\server\routes\editAccountRouter.js
[0] - C:\Users\Administrator\snaily-cadv2\server\server.js
[0]     at Function.Module._resolveFilename
(internal/modules/cjs/loader.js:966:15)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:842:27)
[0]     at Module.require (internal/modules/cjs/loader.js:1026:19)
[0]     at require (internal/modules/cjs/helpers.js:72:18)
[0]     at Object.<anonymous>
(C:\Users\Administrator\snaily-cadv2\server\node_modules\bcrypt\bcrypt.js:6:16)
[0]     at Module._compile (internal/modules/cjs/loader.js:1138:30)
[0]     at Object.Module._extensions..js
(internal/modules/cjs/loader.js:1158:10)
[0]     at Module.load (internal/modules/cjs/loader.js:986:32)
[0]     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
[0]     at Module.require (internal/modules/cjs/loader.js:1026:19) {
[0]   code: 'MODULE_NOT_FOUND',
[0]   requireStack: [
[0]
'C:\\Users\\Administrator\\snaily-cadv2\\server\\node_modules\\bcrypt\\bcrypt.js',
[0]
'C:\\Users\\Administrator\\snaily-cadv2\\server\\routes\\editAccountRouter.js',
[0]     'C:\\Users\\Administrator\\snaily-cadv2\\server\\server.js'
[0]   ]
[0] }
[0] [nodemon] app crashed - waiting for file changes before starting...

Den ons 3 juni 2020 kl 07:12 skrev Casper <notifications@github.com>:

**Comment by casperiv0** [comment]
Hello! 

I see there's 2 things, 

1. I think it's not allowing you too install the required packages because you're in the `Administrator` folder, try to reinstall the CAD in you're `documents` or `desktop`
2. something went wrong with adding the `serve` command, after you've tried reinstalling the CAD, run `npm run build` and then `yarn global add serve` in the `client` folder, It's should also say this: 
![image](https://user-images.githubusercontent.com/53900565/83637139-63296480-a5a7-11ea-9e6b-35dd526b6246.png)

also sorry for the inconvenience!

**Comment by nightking2002** [comment]
Yea downloaded it on the desktop seems to work! Thanks alot


Den ons 3 juni 2020 kl 14:36 skrev Casper <notifications@github.com>:

**Comment by casperiv0** [comment]
Alright cool! No Problem!
